### ISSUE TITLE
Error beim Ausführen des Skript "GenerateSimulinkThermalModel.mlx"

### ISSUE THREAD

**Issue by bernehnl** [mathworks/import-motorcad-thermal-simulink#1]
Beim Ausführen des Skript "GenerateSimulinkThermalModel.mlx" erhalte ich folgende Fehlermeldung:
![image](https://user-images.githubusercontent.com/122378972/211585296-8b2b14de-aede-4d1b-87da-3f5b87a78261.png)
Hatte schon einmal jemand ein ähnliches Problem?

**Comment by angel-boschdom** [comment]
Thanks for reporting this issue. The root cause is the MatrixTextSeparator property in Motor-CAD is set to ";" in your computer, but this repository expected a ",". I will soon update the repository so that it works correctly regardless of the MatrixTextSeparator value.

**Comment by angel-boschdom** [comment]
This is fixed in Release R2021b update 1.2 (tag 21.2.1.2)
