### ISSUE TITLE
Details about required Matlab products

### ISSUE THREAD

**Issue by cristianbabetto** [mathworks/import-motorcad-thermal-simulink#2]
Hi,

Currently, I don't have a Matlab license so I cannot check the requirements.
I would like to know in which step of the process the product "Motor Control Blockset™" is needed?
Is it always mandatory?
Is it possible to include additional details about the products required in the description of the tool?

thanks

**Comment by angel-boschdom** [comment]
Resolved in https://github.com/mathworks/import-motorcad-thermal-simulink/commit/528a8d4aac64e5136fcaabf1b99f1b81a57f224a
